version: '3.4'

services:
  orderapiapp:
    image: ${DOCKER_REGISTRY-}orderapiapp
    build:
      context: .
      dockerfile: OrderApiApp/Dockerfile

    container_name: app_container
    ports:
      - 8080:80
      - 8000:443

    networks:
      - internal

    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: db_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

    networks:
      - internal

networks:
  internal:
    driver: bridge 

